# Generated by Django 2.2.12 on 2020-05-10 14:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("timesheetbot", "0004_auto_20200510_1647"),
    ]

    operations = [
        migrations.AlterField(
            model_name="timeentry",
            name="is_cii",
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name="timeentry",
            name="is_cir",
            field=models.BooleanField(default=False, null=True),
        ),
    ]
