# Generated by Django 4.1.2 on 2022-11-24 10:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("timesheetbot", "0006_user_working_timezone"),
    ]

    operations = [
        migrations.CreateModel(
            name="Program",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slack_value", models.CharField(max_length=15, unique=True)),
                ("slack_description", models.CharField(max_length=63, unique=True)),
                ("spreadsheet_value", models.CharField(max_length=15, unique=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
        ),
        migrations.RenameField(
            model_name="timeentry",
            old_name="activities",
            new_name="description",
        ),
        migrations.RemoveField(
            model_name="timeentry",
            name="is_cii",
        ),
        migrations.RemoveField(
            model_name="timeentry",
            name="is_cir",
        ),
        migrations.RemoveField(
            model_name="timeentry",
            name="is_holiday",
        ),
        migrations.AddField(
            model_name="timeentry",
            name="program",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="timesheetbot.program",
            ),
        ),
    ]
