# Generated by Django 4.1.2 on 2022-11-30 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "timesheetbot",
            "0007_program_rename_activities_timeentry_description_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="worktype",
            name="slack_description",
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="worktype",
            name="slack_value",
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name="worktype",
            name="spreadsheet_value",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
