# Generated by Django 4.1.3 on 2022-12-06 07:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "timesheetbot",
            "0007_program_rename_activities_timeentry_description_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="spreadsheet_top_left_row",
            new_name="spreadsheet_top_row",
        ),
        migrations.RemoveField(
            model_name="user",
            name="slack_username",
        ),
    ]
