# Generated by Django 4.1.2 on 2022-11-30 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("timesheetbot", "0008_alter_worktype_slack_description_and_more"),
    ]

    operations = [
        migrations.RunSQL("UPDATE timesheetbot_worktype SET is_active=false;"),
        migrations.RunSQL(
            """INSERT INTO timesheetbot_worktype (slack_value, slack_description, spreadsheet_value, is_active) VALUES
                ('meeting_planning', 'Meeting - planning : sprints, scrums, OKRs, operations else', 'Meeting - planning : sprints, scrums, OKRs, operations else', True),
                ('meeting_worskhop', 'Meeting - worskhop : peer programming, working together', 'Meeting - worskhop : peer programming, working together', True),
                ('meeting_admin', 'Meeting - admin : other NA to a program', 'Meeting - admin : other NA to a program', True),
                ('meeting_sales', 'Meeting - sales : other NA to a program', 'Meeting - sales : other NA to a program', True),
                ('meeting_customer_support_1', 'Meeting - customer support : planning roadmap, co-construction, Comop, Copil, follow-up', 'Meeting - customer support : planning roadmap, co-construction, Comop, Copil, follow-up', True),
                ('meeting_customer_support_2', 'Meeting - customer support : other NA such as demo of a feature, issue, etc.', 'Meeting - customer support : other NA such as demo of a feature, issue, etc.', True),
                ('meeting_other', 'Meeting - other', 'Meeting - other', True),
                ('development_new_feature', 'Development - new feature', 'Development - new feature', True),
                ('development_bug_fixes', 'Development - bug fixes', 'Development - bug fixes', True),
                ('development_backend', 'Development - backend', 'Development - backend', True),
                ('development_datascience', 'Development - datascience', 'Development - datascience', True),
                ('development_other', 'Development - other', 'Development - other', True),
                ('study_r&dStudy - R&D', 'Study - R&D', '', True),
                ('study_other', 'Study - other', 'Study - other', True),
                ('operations_data_building_1', 'Operations - data building : transcription', 'Operations - data building : transcription', True),
                ('operations_data_building_2', 'Operations - data building : classification', 'Operations - data building : classification', True),
                ('operations_data_building_3', 'Operations - data building : calls qm evaluations', 'Operations - data building : calls qm evaluations', True),
                ('operations_data_building_4', 'Operations - data building : other', 'Operations - data building : other', True);
            """
        ),
    ]
