# Generated by Django 4.1.3 on 2023-04-04 15:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "timesheetbot",
            "0008_rename_spreadsheet_top_left_row_user_spreadsheet_top_row_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="slack_republish_hook",
        ),
    ]
