# Generated by Django 4.1.3 on 2023-04-04 16:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("timesheetbot", "0009_remove_user_slack_republish_hook"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="do_send_copy_of_data",
        ),
    ]
