# Generated by Django 4.1.2 on 2022-11-30 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("timesheetbot", "0009_new_work_types"),
    ]

    operations = [
        migrations.RunSQL(
            """INSERT INTO timesheetbot_program (slack_value, slack_description, spreadsheet_value, is_active) VALUES
                ('cir', '*CIR*: _R&D activities_', 0, True),
                ('cii', '*CII*: _new features/ideas for the product_', 1, True),
                ('project_1', '*Project 1*: _Aqua_', 2, True),
                ('project_2', '~*Project 2*: :soon:~', 3, True),
                ('sick', '*Sick* :face_with_thermometer:', 4, True),
                ('holiday', '*Holiday* :palm_tree:', 5, True),
                ('none', '_None of them_', 6, True);
            """
        ),
    ]
