# Generated by Django 4.1.2 on 2022-11-30 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("timesheetbot", "0010_new_programs"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="program",
            name="spreadsheet_value",
        ),
        migrations.AddField(
            model_name="program",
            name="spreadsheet_cell_gap",
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
    ]
