version: '3'

volumes:
  timesheetbot_pgdata:
    external: true

services:
  postgres:
    image: postgres:alpine
    environment:
      POSTGRES_DB: timesheetbot
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: dev
    ports:
      - 5432:5432
    volumes:
      - timesheetbot_pgdata:/var/lib/postgresql/data
