version: '3'

volumes:
  batvoice_cir_pgdata:
    external: true

services:
  postgres:
    image: postgres:10-alpine
    environment:
      - POSTGRES_PASSWORD=cir_default_root_password
    network_mode:
      host
    ports:
      - 5432:5432
    volumes:
      - batvoice_cir_pgdata:/var/lib/postgresql/data
