apiVersion: batch/v1
kind: CronJob
metadata:
  name: timesheetbot-updater
  labels:
    app: timesheetbot
spec:
  concurrencyPolicy: Forbid
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: timesheetbot
          name: timesheetbot-updater
        spec:
          containers:
          - name: timesheetbot-updater
            image: 367353094751.dkr.ecr.eu-west-1.amazonaws.com/timesheetbot:{{ .Values.docker.tag }}
            args:
            - /app/timesheetbot/manage.py
            - perform_hourly_tasks
            command:
            - /env/bin/python
            env:
            {{- range $k, $v := .Values.env }}
            - name: {{ $k }}
              value: {{ $v | quote -}}
            {{- end }}
            - name: HOSTNAME
              value: {{ .Values.ingress.host }}
            - name: GSPREAD_ACCESS_CONF_LOCATION
              value: /etc/mounted_secrets/client_secret.json
            imagePullPolicy: IfNotPresent
            resources:
              limits:
                memory: 150Mi
              requests:
                memory: 150Mi
            volumeMounts:
            - mountPath: /etc/mounted_secrets
              name: timesheetbot
          restartPolicy: Never
          nodeSelector:
            role: worker
          tolerations:
          - effect: NoSchedule
            key: instancetype
            value: worker
          volumes:
          - name: timesheetbot
            secret:
              defaultMode: 292
              secretName: timesheetbot
  schedule: 11 * * * *
  successfulJobsHistoryLimit: 1
  suspend: true
