apiVersion: v1
kind: Service
metadata:
  name: timesheetbot
  labels:
    app: timesheetbot
    client: batvoice
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  selector:
    app: timesheetbot
