AFTERNOON_ENDS_AT: 19
DJANGO_DEBUG_MODE: true
DJANGO_SECURITY_KEY: dd48w8!+ih^%drjg3*bk0b^y_m*sxc4gs@xg81tdtn3m^bu3op
GSPREAD_SHEET:
GSPREAD_ACCESS_CONF_LOCATION: /etc/gspread_client_secret.json
HOSTNAME: localhost
MORNING_ENDS_AT: 13
POSTGRES_NAME: timesheetbot
POSTGRES_PASSWORD: dev
POSTGRES_SERVICE_HOST: localhost
POSTGRES_SERVICE_PORT: 5432
POSTGRES_USER: dev
SKIP_NOTIFICATIONS_ON_WE: true
SLACK_BEARER_TOKEN: dummy_slack_token
SLACK_QUERY_MAX_AGE_SECONDS: 60
SLACK_SIGNING_SECRET: dummy_slack_signing_secret
SLACK_CHAT_API_URL: https://slack.com/api/chat.postMessage
SLACK_VIEW_API_URL: https://slack.com/api/views.open
SPREADSHEET_PROGRAM_FIRST_COLUMN: E
SPREADSHEET_PROGRAM_LATEST_COLUMN: K
WORKING_TIMEZONE: CET
